check rds backend existance

diff --git a/.github/workflows/backend-ec2.yml b/.github/workflows/backend-ec2.yml
--- a/.github/workflows/backend-ec2.yml
+++ b/.github/workflows/backend-ec2.yml
@@ -111,18 +111,21 @@ jobs:
 
       - name: 'Fetch RDS Endpoint from Terraform State'
         id: get_rds_endpoint
+        if: env.state_exists == 'true'
         run: |
-          if [[ "$state_exists" == "true" ]]; then
-            rds_private_address=$(terraform output -state=./terraform.tfstate -raw rds_private_address)
-            echo "rds_private_address=$rds_private_address" >> $GITHUB_ENV
+          # Fetch RDS private address
+          rds_private_address=$(terraform output -state=./terraform.tfstate -raw rds_private_address 2>/dev/null)
+          if [ -z "$rds_private_address" ]; then
+            echo "RDS private address not found in Terraform state!"
+            exit 1
           else
-            echo "State file does not exist, skipping RDS endpoint fetch."
+            echo "rds_private_address=$rds_private_address" >> $GITHUB_ENV
           fi
-
+          
           # Fetch RDS DB name
           rds_db_name=$(terraform output -state=./terraform.tfstate -raw rds_db_name 2>/dev/null)
           echo "rds_db_name=$rds_db_name" >> $GITHUB_ENV
-    
+          
           # Fetch RDS endpoint
           rds_endpoint=$(terraform output -state=./terraform.tfstate -raw rds_endpoint 2>/dev/null)
           echo "rds_endpoint=$rds_endpoint" >> $GITHUB_ENV
