Update vpc-workflow.yml

diff --git a/.github/workflows/vpc-workflow.yml b/.github/workflows/vpc-workflow.yml
--- a/.github/workflows/vpc-workflow.yml
+++ b/.github/workflows/vpc-workflow.yml
@@ -12,13 +12,29 @@ jobs:
         uses: actions/checkout@v4
 
       - name: 'Download S3 Bucket Artifact'
+        id: download_artifact
         uses: actions/download-artifact@v3
         with:
           name: s3-bucket-name
+        continue-on-error: true
+
+      - name: 'Check if Artifact Downloaded'
+        run: |
+          if [ -f s3_bucket_name.txt ]; then
+            echo "Artifact downloaded successfully."
+          else
+            echo "Artifact download failed or file does not exist."
+          fi
 
       - name: 'Read S3 Bucket Name'
-        run: echo "s3_bucket=$(cat s3_bucket_name.txt)" >> $GITHUB_ENV
-
+        run: |
+          if [ -f s3_bucket_name.txt ]; then
+            echo "s3_bucket=$(cat s3_bucket_name.txt)" >> $GITHUB_ENV
+          else
+            echo "No bucket name found. Exiting."
+            exit 1  # Exit if the file doesn't exist
+          fi
+          
       - name: 'Setup Terraform'
         uses: hashicorp/setup-terraform@v3
         with:
